"""added action field to the model

Revision ID: 4fa85443a7ff
Revises: c7882ee9b2ef
Create Date: 2021-07-28 21:51:07.210857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fa85443a7ff'
down_revision = 'c7882ee9b2ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('unfulfilled_messages', sa.Column('action', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('unfulfilled_messages', 'action')
    # ### end Alembic commands ###
